/**
 * Viewport culling for big GeoJSON layers.
 *
 * Personal use only, not for distribution or resale; not for navigation.
 *
 * THE PROBLEM THIS EXISTS FOR
 *
 * Murrells Inlet ships 29,676 contours and 26,288 depth polygons, and both layers were handed
 * to L.geoJSON whole. Leaflet's canvas is comfortable to roughly 10,000 paths and sluggish past
 * 20,000, so selecting that zone built ~56,000 and the map stopped responding before anything
 * could be looked at. Charleston is worse. The pack is not the problem here -- even a perfectly
 * cut coastal boundary leaves more marsh detail than one screen can use.
 *
 * A feature's bounding box is computed ONCE and cached on the feature itself, because the cull
 * runs on every pan and walking 3 million vertices per pan would cost more than the drawing it
 * is meant to avoid. The cache is a non-enumerable property so it never reaches JSON.stringify,
 * IndexedDB, or a structuredClone of the layer.
 */

const BB = Symbol('bbox');

function walk(coords, out) {
  if (!Array.isArray(coords)) return;
  if (typeof coords[0] === 'number') {
    const [x, y] = coords;
    if (x < out[0]) out[0] = x;
    if (y < out[1]) out[1] = y;
    if (x > out[2]) out[2] = x;
    if (y > out[3]) out[3] = y;
    return;
  }
  for (const c of coords) walk(c, out);
}

export function featureBBox(feat) {
  if (!feat) return null;
  if (feat[BB]) return feat[BB];
  const g = feat.geometry;
  if (!g || !g.coordinates) return null;
  const out = [Infinity, Infinity, -Infinity, -Infinity];
  walk(g.coordinates, out);
  if (!Number.isFinite(out[0])) return null;
  Object.defineProperty(feat, BB, { value: out, enumerable: false, configurable: true });
  return out;
}

/**
 * A predicate for Array.filter that keeps features overlapping the map view.
 *
 * `pad` is a fraction of the view added on every side, so a small pan does not immediately
 * expose blank water while the redraw is still debounced. Returns null when the map is not
 * ready, and callers treat null as "draw everything" rather than "draw nothing" -- failing
 * open, because an empty map looks like a bug and a slow map looks like a slow map.
 */
export function viewFilter(map, pad = 0.25) {
  if (!map || typeof map.getBounds !== 'function') return null;
  let b;
  try { b = map.getBounds().pad(pad); } catch { return null; }
  const w = b.getWest(), s = b.getSouth(), e = b.getEast(), n = b.getNorth();
  return (feat) => {
    const bb = featureBBox(feat);
    if (!bb) return true;
    return bb[0] <= e && bb[2] >= w && bb[1] <= n && bb[3] >= s;
  };
}

export function cull(features, map, pad = 0.25) {
  const f = viewFilter(map, pad);
  return f ? features.filter(f) : features;
}

// A coastal zone's bbox is its CLIP RECTANGLE, not its water. Murrells Inlet's box is 24 x 33
// miles and fitting it lands the map around zoom 11, where the pack's ~56,000 contour and depth
// features all fall inside the view at once and the map stops responding. Zoom 14 is roughly a
// 7 mile view -- about 10,000 features, where Leaflet's canvas is still comfortable -- centred
// on the same point fitBounds would have centred on.
//
// This is a symptom fix and it says so. The repair is giving coastal zones an inshore boundary
// instead of a rectangle, at which point the box is worth fitting again.
// See COASTAL_ZONES_CLIP_TO_A_RECTANGLE_2026-08-07.md.
//
// It lives HERE and not in js/data/coastal-zones.js because that file is GENERATED by
// Scripts/gen_coastal_zones_js.py -- a hand-edit there survives until the next regeneration and
// then vanishes without a word. coastal-zones-parity.test.js caught this within one run.
export const COASTAL_LANDING_ZOOM = 14;

export function landOnCoastalZone(map, bbox) {
  if (!map || !Array.isArray(bbox) || bbox.length !== 2) return false;
  const [[s, w], [n, e]] = bbox;
  if (![s, w, n, e].every(Number.isFinite)) return false;
  map.setView([(s + n) / 2, (w + e) / 2], COASTAL_LANDING_ZOOM);
  return true;
}
