#!/usr/bin/env python3
"""
migrate_merged_slugs.py -- carry a merge through every registry sidecar keyed by slug.

WHY
    merge_duplicate_waters.py rewrote lake_index.json and nothing else. Twenty other files in
    registry/ are keyed by the same slugs, and three of them are read by the app. The damage was
    not theoretical: in lake_access.json ALL FOUR keepers were absent and all four retired slugs
    present, so the merge orphaned the access data for every water it merged.

TWO SITUATIONS, AND THEY ARE NOT THE SAME
    RENAME   the retired slug is present and the keeper is not -- lake_access.json. Move it.
    COLLIDE  both are present -- water_bindings.json. The keeper's entry is kept and the retired
             one is REPORTED, never silently dropped, because picking a winner between two
             populated records is not a decision a script should make quietly.

WHAT IT WILL NOT DO
    It does not touch lake_index.json (already merged), .bak files, or the dated _before_
    snapshots, which are history and must keep saying what they said. Files that are cheaply
    regenerated by a build script -- water_chain.json, _nhd_bindings.json -- are better re-run
    than patched; pass --include-derived only if you would rather patch them.

    Dry run by default. Every file it rewrites gets a .bak first.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

REGISTRY_REL = 'registry/lake_index.json'
# Regenerated by a script; re-running beats patching, so they are skipped unless asked for.
DERIVED = {'water_chain.json', '_nhd_bindings.json', '_duplicate_candidates.json'}


def find_repo_root(explicit=None):
    if explicit:
        p = Path(explicit)
        return p.parent.parent if p.name.endswith('.json') else p
    here = Path.cwd().resolve()
    mine = Path(__file__).resolve().parent
    seen = set()
    for cand in [here] + list(here.parents) + [mine] + list(mine.parents):
        if cand in seen:
            continue
        seen.add(cand)
        if (cand / REGISTRY_REL).exists():
            return cand
    return here


def skip(name):
    return (name in ('lake_index.json', '_merge_decisions.json', '_deletion_tab.json')
            or name.endswith('.bak')
            or '_before' in name
            or 'before_split' in name)


def migrate_obj(obj, pairs, path, actions, fold=False):
    """Rewrite one dict's keys in place at this level. pairs is {retired: keeper}."""
    for retired, keeper in pairs.items():
        if retired not in obj:
            continue
        if keeper in obj:
            a, b = obj[keeper], obj[retired]
            extra, filled = set(), set()
            if isinstance(a, dict) and isinstance(b, dict):
                extra = set(b) - set(a)
                filled = {k for k in set(b) & set(a)
                          if a.get(k) in (None, '', [], {}) and b.get(k) not in (None, '', [], {})}
            covered = (a == b
                       or (hasattr(b, '__len__') and len(b) == 0)
                       or (isinstance(a, dict) and isinstance(b, dict)
                           and not extra and not filled))
            if fold and (extra or filled):
                for k in sorted(extra | filled):
                    a[k] = b[k]
            actions.append({'path': path, 'retired': retired, 'keeper': keeper,
                            'covered': covered,
                            'extra': sorted(extra), 'filled': sorted(filled),
                            'folded': bool(fold and (extra or filled)),
                            'action': ('nothing the keeper lacks' if covered else
                                       ('folded into the keeper' if fold
                                        else 'KEEPER KEPT, THIS CONTENT DROPPED')),
                            'dropped': None if covered else summarize(b)})
            del obj[retired]
        else:
            obj[keeper] = obj.pop(retired)
            actions.append({'path': path, 'retired': retired, 'keeper': keeper,
                            'covered': True, 'extra': [], 'filled': [], 'folded': False,
                            'action': 'renamed onto the keeper', 'dropped': None})


def summarize(v):
    if isinstance(v, dict):
        return f'dict with {len(v)} key(s): ' + ', '.join(list(v)[:6])
    if isinstance(v, list):
        return f'list of {len(v)}'
    return repr(v)[:120]


def walk(data, pairs, actions, prefix='', fold=False):
    """Top level, then one level of nesting -- which is where every real case lives
    (lakes.*, bindings.*, packs.*, by_lake.*, slug_to_r2_key.*)."""
    if not isinstance(data, dict):
        return
    migrate_obj(data, pairs, prefix or '<top>', actions, fold)
    for k, v in list(data.items()):
        if isinstance(v, dict):
            migrate_obj(v, pairs, f'{prefix}{k}', actions, fold)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--registry', default=None)
    ap.add_argument('--decisions', required=True)
    ap.add_argument('--include-derived', action='store_true',
                    help='also patch files a build script regenerates')
    ap.add_argument('--fold', action='store_true',
                    help='on a collision, copy across keys the keeper lacks or has empty')
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args()

    root = find_repo_root(args.registry)
    dec = json.loads(Path(args.decisions).read_text(encoding='utf-8'))
    merges = dec.get('merges', dec) if isinstance(dec, dict) else dec
    pairs = {m['retire']: m['keep'] for m in merges if m.get('retire') and m.get('keep')}
    print(f'merges: {len(pairs)}')
    for r, k in pairs.items():
        print(f'   {r}  ->  {k}')

    reg_dir = root / 'registry'
    files = sorted(p for p in reg_dir.glob('*.json') if not skip(p.name))
    if not args.include_derived:
        skipped = [p.name for p in files if p.name in DERIVED]
        files = [p for p in files if p.name not in DERIVED]
        if skipped:
            print(f'\nskipping {len(skipped)} regenerated file(s): {", ".join(skipped)}')
            print('   re-run their build script instead, or pass --include-derived')

    total, touched = [], 0
    for p in files:
        try:
            data = json.loads(p.read_text(encoding='utf-8'))
        except Exception as e:
            print(f'   {p.name}: unreadable ({type(e).__name__}), skipped')
            continue
        actions = []
        walk(data, pairs, actions, fold=args.fold)
        if not actions:
            continue
        touched += 1
        loud = [a for a in actions if not a['covered']]
        if loud:
            print(f'\n== {p.name}')
            for a in loud:
                print(f'   {a["path"]}.{a["retired"]} -> {a["keeper"]}: {a["action"]}')
                if a['extra']:
                    print(f'      keeper lacks these keys: {a["extra"]}')
                if a['filled']:
                    print(f'      keeper has these empty : {a["filled"]}')
                if a['dropped'] and not a['folded']:
                    print(f'      DROPPED: {a["dropped"]}')
        total.extend([dict(a, file=p.name) for a in actions])
        if args.write:
            shutil.copy2(p, p.with_suffix('.json.bak'))
            p.write_text(json.dumps(data, indent=1), encoding='utf-8')

    renamed = sum(1 for a in total if a['action'] == 'renamed onto the keeper')
    quiet = sum(1 for a in total if a['covered'] and a['action'] != 'renamed onto the keeper')
    folded = sum(1 for a in total if a['folded'])
    lost = sum(1 for a in total if not a['covered'] and not a['folded'])
    print(f'\n== {touched} file(s) affected')
    print(f'   {renamed:>4} renamed onto the keeper (the keeper had no entry)')
    print(f'   {quiet:>4} collision(s) carrying nothing the keeper lacks -- no action needed')
    if folded:
        print(f'   {folded:>4} collision(s) FOLDED into the keeper')
    if lost:
        print(f'   {lost:>4} collision(s) holding content the keeper lacks, listed above.')
        print('        Re-run with --fold to copy those keys across, or leave them if the')
        print('        retired entry describes something being deleted anyway.')
    else:
        print('      0 collisions would lose anything.')
    if args.write:
        print(f'\nwrote {touched} file(s), each with a .bak beside it')
    else:
        print('\nDRY RUN -- nothing written. Add --write.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
