#!/usr/bin/env python3
"""
migrate_merged_slugs.py -- carry a merge through every registry sidecar keyed by slug.

WHY
    merge_duplicate_waters.py rewrote lake_index.json and nothing else. Twenty other files in
    registry/ are keyed by the same slugs, and three of them are read by the app. The damage was
    not theoretical: in lake_access.json ALL FOUR keepers were absent and all four retired slugs
    present, so the merge orphaned the access data for every water it merged.

TWO SITUATIONS, AND THEY ARE NOT THE SAME
    RENAME   the retired slug is present and the keeper is not -- lake_access.json. Move it.
    COLLIDE  both are present -- water_bindings.json. The keeper's entry is kept and the retired
             one is REPORTED, never silently dropped, because picking a winner between two
             populated records is not a decision a script should make quietly.

A BOUNDARY IS A FILE, WHICH IS NEITHER A KEY NOR A VALUE
    A key moves. A value is repointed. registry/boundaries/<slug>.geojson is a third thing
    and this tool never opened that directory, so a merge moved falls_lake's NAME and left
    it tracing 9,529.6 acres while brinkley_lake, the slug it retired, held 12,958 beside
    it. --boundaries is that third pass, and it adopts on CONTAINMENT rather than on size.
    See carry_boundaries().

A SLUG IS ALSO A VALUE, AND UNTIL --values THIS TOOL COULD NOT SEE THAT
    Everything above rewrites KEYS. A slug travels as a VALUE too -- an element of
    tile_lake_map's by_tile[], an `alias_of` in _river_aliases.json, the R2 key a slug maps to
    in key_map.json, the `slug` field inside a record whose key this tool already renamed --
    and none of those move when the key does. Measured after the seven merges of 2026-08-17:
    ZERO retired keys left anywhere and 183 retired values, across nine files, four of which
    are published. The tool said the migration was complete and it was half done, which is the
    same shape as the list-fold bug it already carries a comment about.

    --values is that half. See retarget(), and LEAVE_ALONE for the four files it will not
    touch even so.

WHAT IT WILL NOT DO
    It does not touch lake_index.json (already merged), .bak files, or the dated _before_
    snapshots, which are history and must keep saying what they said. Files that are cheaply
    regenerated by a build script -- water_chain.json, _nhd_bindings.json -- are better re-run
    than patched; pass --include-derived only if you would rather patch them.

    Dry run by default. Every file it rewrites gets a .bak first.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

REGISTRY_REL = 'registry/lake_index.json'
# Regenerated by a script; re-running beats patching, so they are skipped unless asked for.
DERIVED = {'water_chain.json', '_nhd_bindings.json', '_duplicate_candidates.json'}

# Files whose retired slugs are REPORTED and never rewritten. Each one describes a world the
# merge did not change, so editing it makes the record agree with the registry while the thing
# it describes still disagrees. The reason is carried per file because they are not the same
# reason, and a single name like "skip" would hide that.
#
# lakes.json is the one that is easy to get wrong, and I did. It looks like an ordinary registry
# sidecar and it is not: consolidate_lake_index.py:drop_retired() says it out loud -- lakes.json
# is the record of what EXISTS and a merge is a statement about what the app OFFERS. That is why
# consolidate carries a gate to keep merged slugs OUT of the index it builds from lakes.json,
# rather than editing lakes.json. Rewriting its by_state lists on 2026-08-18 left seven records
# in lakes[] belonging to no state list at all: the inventory disagreeing with its own index.
LEAVE_ALONE = {
    '_r2_listing.json': 'records what the R2 bucket actually holds, and it is what '
                        'prune_r2_keys.py reads to find the objects a merge left behind',
    '_registry_state.json': 'records what a run reported, on the day it ran',
    '_water_bindings_review.json': 'records what a run reported, on the day it ran',
    'lakes.json': 'the 3DHP inventory of what EXISTS -- a merge changes what the app OFFERS, '
                  'which is what consolidate_lake_index.py gates on instead',
}

# Fields whose value NAMES the record it sits in, rather than pointing at another one.
IDENTITY_FIELDS = ('slug', 'lake_id')

# Value hits printed in full per file before the rest is grouped by kind.
VALUE_LINES = 12


def find_repo_root(explicit=None):
    if explicit:
        p = Path(explicit)
        return p.parent.parent if p.name.endswith('.json') else p
    here = Path.cwd().resolve()
    mine = Path(__file__).resolve().parent
    seen = set()
    for cand in [here] + list(here.parents) + [mine] + list(mine.parents):
        if cand in seen:
            continue
        seen.add(cand)
        if (cand / REGISTRY_REL).exists():
            return cand
    return here


def skip(name):
    return (name in ('lake_index.json', '_merge_decisions.json', '_deletion_tab.json')
            or name.endswith('.bak')
            or '_before' in name
            or 'before_split' in name)


def migrate_obj(obj, pairs, path, actions, fold=False):
    """Rewrite one dict's keys in place at this level. pairs is {retired: keeper}."""
    for retired, keeper in pairs.items():
        if retired not in obj:
            continue
        if keeper in obj:
            a, b = obj[keeper], obj[retired]
            extra, filled, appended = set(), set(), []
            if isinstance(a, dict) and isinstance(b, dict):
                extra = set(b) - set(a)
                filled = {k for k in set(b) & set(a)
                          if a.get(k) in (None, '', [], {}) and b.get(k) not in (None, '', [], {})}
            elif isinstance(a, list) and isinstance(b, list):
                # A LIST IS A COLLECTION, NOT A CHOICE. Only the dict branch above existed, so
                # when both sides were lists nothing was ever carried: extra and filled stayed
                # empty, covered came out False, and `del obj[retired]` threw the retiree's list
                # away while the report said "folded into the keeper". That is how Rembert C.
                # Dennis Landing was lost on 2026-08-17 when wadboo_creek folded into
                # cooper_river -- the keeper already had a ramp list, so the retiree's list of
                # one was dropped. The same message had appeared once before over a duplicate
                # GMP tile and been harmless, which is exactly why it went unquestioned.
                def _key(x):
                    return x if isinstance(x, str) else json.dumps(x, sort_keys=True)
                seen = {_key(x) for x in a}
                appended = [x for x in b if _key(x) not in seen]
            covered = (a == b
                       or (hasattr(b, '__len__') and len(b) == 0)
                       or (isinstance(a, dict) and isinstance(b, dict)
                           and not extra and not filled)
                       or (isinstance(a, list) and isinstance(b, list) and not appended))
            if fold:
                for k in sorted(extra | filled):
                    a[k] = b[k]
                if appended:
                    a.extend(appended)
            actions.append({'path': path, 'retired': retired, 'keeper': keeper,
                            'covered': covered, 'appended': len(appended),
                            'extra': sorted(extra), 'filled': sorted(filled),
                            'folded': bool(fold and (extra or filled or appended)),
                            'action': ('nothing the keeper lacks' if covered else
                                       ('folded into the keeper' if fold
                                        else 'KEEPER KEPT, THIS CONTENT DROPPED')),
                            'dropped': None if covered else summarize(b)})
            del obj[retired]
        else:
            obj[keeper] = obj.pop(retired)
            actions.append({'path': path, 'retired': retired, 'keeper': keeper,
                            'covered': True, 'extra': [], 'filled': [], 'folded': False,
                            'action': 'renamed onto the keeper', 'dropped': None})


def summarize(v):
    if isinstance(v, dict):
        return f'dict with {len(v)} key(s): ' + ', '.join(list(v)[:6])
    if isinstance(v, list):
        return f'list of {len(v)}'
    return repr(v)[:120]


def names_retired(v, pairs):
    """(retired, keeper, prefixed) if this string names a retired slug, else None.

    `prefixed` is the `slug:cooper_river` spelling lakes.json uses for lake_id. A bare compare
    misses it, and missing it is how a zombie row keeps a working id after its slug is gone.
    """
    if not isinstance(v, str):
        return None
    for retired, keeper in pairs.items():
        if v == retired:
            return retired, keeper, False
        if v == 'slug:' + retired:
            return retired, keeper, True
    return None


def identifies(rec, slug):
    """Does this record identify itself as `slug`, in either spelling?"""
    if not isinstance(rec, dict):
        return False
    return any(rec.get(f) in (slug, 'slug:' + slug) for f in IDENTITY_FIELDS)


def retarget(node, pairs, hits, path='', rewrite=False, parent_key=None, skip=()):
    """Rewrite slug VALUES at any depth. The half migrate_obj cannot see.

    THREE SHAPES, AND THEY ARE NOT THE SAME.

    list item   A REFERENCE -- by_tile['B4E0FC'], by_state['SC']. In all nine real cases the
                keeper was ALREADY in the list beside the retired slug, so renaming in place
                would have produced a duplicate. The retired element is dropped instead, and
                renamed only when the keeper is genuinely absent.

    field       A REFERENCE -- `alias_of`, and key_map's slug_to_r2_key values. Rewritten to
                the keeper. slug_to_r2_key is an identity map in 1,547 of its 1,551 entries;
                the four exceptions are exactly the four merges, each keeper pointing at the
                R2 key of the slug it retired. That works only until the deletion tab runs.

    identity    The value NAMES the record it sits in. Two cases, and the difference is whether
                anything else already answers to the keeper:

                  under a keeper KEY -- water_bindings.json bindings/cooper_river/slug still
                  read 'tail_race_canal' after migrate_obj renamed the key above it. The record
                  is the keeper's; the field is stale; realign it. Read the field that travels
                  with the value.

                  in a LIST beside a sibling that already carries the keeper -- lakes.json holds
                  a full record for cooper_river AND the two it absorbed. Rewriting makes three
                  records claiming one slug. This is a ZOMBIE ROW: reported for the deletion tab
                  and neither rewritten nor deleted here, because deleting is Ryan's call and
                  it happens at the end.
    """
    if isinstance(node, dict):
        for k, v in list(node.items()):
            if k in skip:
                continue
            p = '%s/%s' % (path, k)
            m = names_retired(v, pairs)
            if m is None:
                retarget(v, pairs, hits, p, rewrite, parent_key=k)
                continue
            retired, keeper, prefixed = m
            new = ('slug:' + keeper) if prefixed else keeper
            if k in IDENTITY_FIELDS and parent_key != keeper:
                hits.append({'kind': 'identity', 'path': p, 'retired': retired, 'keeper': keeper,
                             'wrote': False, 'writable': False,
                             'why': 'identity of a record whose key is %r, not the keeper'
                                    % (parent_key,)})
                continue
            if rewrite:
                node[k] = new
            hits.append({'kind': ('identity' if k in IDENTITY_FIELDS else 'field'),
                         'path': p, 'retired': retired, 'keeper': keeper,
                         'wrote': rewrite, 'writable': True,
                         'why': ('realigned with the key its record already carries'
                                 if k in IDENTITY_FIELDS else 'reference repointed at the keeper')})
        return

    if isinstance(node, list):
        keep = []
        # What the list WILL hold, tracked separately from `keep` because on a dry run `keep`
        # still carries the old spelling. Testing against `keep` made the dry run report two
        # renames where a write does one rename and one drop -- _water_bindings.json holds both
        # tail_race_canal and wadboo_creek in the same list and both fold to cooper_river. A dry
        # run that does not predict the write is worse than no dry run.
        will_hold = set()
        for i, v in enumerate(node):
            p = '%s[%d]' % (path, i)
            m = names_retired(v, pairs)
            if m is not None:
                retired, keeper, prefixed = m
                new = ('slug:' + keeper) if prefixed else keeper
                if new in node or new in will_hold:
                    hits.append({'kind': 'list-item', 'path': p, 'retired': retired,
                                 'keeper': keeper, 'wrote': rewrite, 'writable': True,
                                 'why': 'dropped -- the keeper is already in this list'})
                    continue
                hits.append({'kind': 'list-item', 'path': p, 'retired': retired, 'keeper': keeper,
                             'wrote': rewrite, 'writable': True,
                             'why': 'renamed in place -- no keeper here yet'})
                will_hold.add(new)
                keep.append(new if rewrite else v)
                continue
            if isinstance(v, str):
                will_hold.add(v)
            zombie = None
            if isinstance(v, dict):
                for f in IDENTITY_FIELDS:
                    z = names_retired(v.get(f), pairs)
                    if z:
                        zombie = z
                        break
            if zombie:
                if any(identifies(x, zombie[1]) for x in node):
                    hits.append({'kind': 'zombie-row', 'path': p, 'retired': zombie[0],
                                 'keeper': zombie[1], 'wrote': False, 'writable': False,
                                 'why': 'a full record for a retired slug sitting beside the '
                                        "keeper's own -- for the deletion tab, not for a rewrite",
                                 'detail': summarize(v)})
                    keep.append(v)
                    continue
                # Nothing else in this list answers to the keeper, so this record IS the
                # keeper's -- the same RENAME migrate_obj does when a key has no collision.
                for f in IDENTITY_FIELDS:
                    z = names_retired(v.get(f), pairs)
                    if not z:
                        continue
                    if rewrite:
                        v[f] = ('slug:' + z[1]) if z[2] else z[1]
                    hits.append({'kind': 'identity', 'path': '%s/%s' % (p, f), 'retired': z[0],
                                 'keeper': z[1], 'wrote': rewrite, 'writable': True,
                                 'why': 'renamed onto the keeper -- no keeper record in this list'})
                # The identity fields are settled; re-walking them would report the same path a
                # second time on a dry run, where nothing was written to stop the second look.
                retarget(v, pairs, hits, p, rewrite, parent_key=parent_key, skip=IDENTITY_FIELDS)
                keep.append(v)
                continue
            retarget(v, pairs, hits, p, rewrite, parent_key=parent_key)
            keep.append(v)
        if rewrite:
            node[:] = keep


def walk(data, pairs, actions, prefix='', fold=False):
    """Top level, then one level of nesting -- which is where every real case lives
    (lakes.*, bindings.*, packs.*, by_lake.*, slug_to_r2_key.*)."""
    if not isinstance(data, dict):
        return
    migrate_obj(data, pairs, prefix or '<top>', actions, fold)
    for k, v in list(data.items()):
        if isinstance(v, dict):
            migrate_obj(v, pairs, f'{prefix}{k}', actions, fold)


def carry_boundaries(reg_dir, pairs, min_cover, write):
    """The third namespace: a boundary is a FILE named for a slug.

    migrate_obj moves a KEY. retarget() repoints a VALUE. A boundary is neither -- it is
    registry/boundaries/<slug>.geojson, and nothing in this tool ever opened that directory.
    So a merge moved the name and left the geometry where it was.

    falls_lake is the case. It kept its name and its 9,529.6-acre partial trace while
    brinkley_lake, the slug it retired, sat beside it holding 12,958: the 3DHP body INLB3
    "Brinkley Lake" at 11,983.6, plus arm LJFWM at 975 acres, whose bounding box sits ENTIRELY
    inside the main body's. A creek arm of the same reservoir, which attach_arms.py had already
    judged part of it. The keeper was missing 2,454 acres of the named body before the arm is
    even counted, and the merge note said so at the time and was not acted on.

    ADOPTED ONLY WHEN THE RETIREE ALL BUT CONTAINS THE KEEPER, and never on size alone. A
    bigger polygon is not automatically the better one -- it can be bigger because it is wrong.
    What makes this safe is containment: brinkley holds 99.84% of falls_lake, so adopting it
    discards 0.16% and gains 36%. Anything below --adopt-min-cover is REPORTED and left, because
    two polygons that disagree about where the water is are a re-tracing decision and this tool
    does not have an opinion about those.

    The residual is always printed, adopted or not. "We kept 99.84% of the old trace" and "we
    kept all of it" are different facts.
    """
    bdir = Path(reg_dir) / 'boundaries'
    if not bdir.is_dir():
        return [], 'no boundaries directory at %s' % bdir
    try:
        from shapely.geometry import shape
        from shapely.ops import unary_union
    except ImportError:
        return [], ('shapely is absent, so containment cannot be tested -- boundaries are '
                    'REPORTED and never adopted. py -m pip install shapely')

    def poly(fp):
        d = json.loads(fp.read_text(encoding='utf-8'))
        feats = d.get('features') if d.get('type') == 'FeatureCollection' else [d]
        gs = [shape(f['geometry']) for f in (feats or [])
              if isinstance(f, dict) and f.get('geometry')]
        return unary_union([g.buffer(0) for g in gs]) if gs else None

    out = []
    for retired, keeper in pairs.items():
        kf, rf = bdir / (keeper + '.geojson'), bdir / (retired + '.geojson')
        if not kf.exists() or not rf.exists():
            continue
        try:
            kp, rp = poly(kf), poly(rf)
        except Exception as exc:
            out.append({'keeper': keeper, 'retired': retired, 'adopted': False,
                        'why': 'unreadable (%s)' % type(exc).__name__})
            continue
        if kp is None or rp is None or kp.is_empty or rp.is_empty:
            continue
        if rp.area <= kp.area * 1.02:
            continue                       # the keeper is already at least as big; nothing to do
        cover = 100.0 * kp.intersection(rp).area / kp.area if kp.area else 0.0
        lost = kp.difference(rp).area / kp.area * 100.0 if kp.area else 0.0
        rec = {'keeper': keeper, 'retired': retired, 'cover': cover, 'lost_pct': lost,
               'gain_pct': 100.0 * (rp.area - kp.area) / kp.area, 'adopted': False}
        if cover < min_cover:
            rec['why'] = ('the retiree holds only %.2f%% of the keeper -- they disagree about '
                          'WHERE the water is, which is a re-tracing decision' % cover)
            out.append(rec)
            continue
        rec['why'] = 'the retiree holds %.2f%% of the keeper and adds %.1f%%' % (cover,
                                                                                 rec['gain_pct'])
        if write:
            shutil.copy2(kf, str(kf) + '.bak')
            doc = json.loads(rf.read_text(encoding='utf-8'))
            feats = doc.get('features') if doc.get('type') == 'FeatureCollection' else [doc]
            geom = (feats[0] or {}).get('geometry') if feats else None
            props = dict(((feats[0] or {}).get('properties') or {}) if feats else {})
            props['slug'] = keeper
            # WHERE THIS SHAPE CAME FROM TRAVELS WITH IT. audit_boundary_rings.py reads
            # `source` to tell a deliberate cut from an unfinished trace, and a boundary that
            # arrived from a retired slug is neither.
            props['source'] = 'adopted from %s.geojson by migrate_merged_slugs.py' % retired
            kf.write_text(json.dumps({'type': 'FeatureCollection', 'features': [
                {'type': 'Feature', 'properties': props, 'geometry': geom}]}), encoding='utf-8')
            rec['adopted'] = True
        out.append(rec)
    return out, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--registry', default=None)
    ap.add_argument('--decisions', required=True)
    ap.add_argument('--include-derived', action='store_true',
                    help='also patch files a build script regenerates')
    ap.add_argument('--fold', action='store_true',
                    help='on a collision, copy across keys the keeper lacks or has empty')
    ap.add_argument('--values', action='store_true',
                    help='also repoint slug VALUES -- list items, alias_of, slug_to_r2_key, and '
                         'the slug field inside a record whose key was already renamed')
    ap.add_argument('--boundaries', action='store_true',
                    help='also carry the BOUNDARY FILE, which is neither a key nor a value')
    ap.add_argument('--adopt-min-cover', type=float, default=99.0,
                    help='adopt the retiree only if it holds this percent of the keeper '
                         '(default 99)')
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args()

    root = find_repo_root(args.registry)
    dec = json.loads(Path(args.decisions).read_text(encoding='utf-8'))
    merges = dec.get('merges', dec) if isinstance(dec, dict) else dec
    pairs = {m['retire']: m['keep'] for m in merges if m.get('retire') and m.get('keep')}
    print(f'merges: {len(pairs)}')
    for r, k in pairs.items():
        print(f'   {r}  ->  {k}')

    reg_dir = root / 'registry'
    # `--registry registry` from the repo root resolved to registry/registry, which does not
    # exist, and glob on a missing directory is empty rather than an error -- so it printed
    # "0 file(s) affected" and read like a clean bill of health. An empty search is not an
    # answer; say which directory was searched and stop.
    if not reg_dir.is_dir():
        sys.exit(f'no registry directory at {reg_dir}\n'
                 f'   --registry takes the path to registry/lake_index.json, or the repo root '
                 f'that CONTAINS registry/. Omit it entirely and it is found from the cwd.')
    files = sorted(p for p in reg_dir.glob('*.json') if not skip(p.name))
    if not files:
        sys.exit(f'{reg_dir} holds no .json files this tool would look at')
    if not args.include_derived:
        skipped = [p.name for p in files if p.name in DERIVED]
        files = [p for p in files if p.name not in DERIVED]
        if skipped:
            print(f'\nskipping {len(skipped)} regenerated file(s): {", ".join(skipped)}')
            print('   re-run their build script instead, or pass --include-derived')

    total, touched, written, vhits = [], 0, 0, []
    for p in files:
        try:
            data = json.loads(p.read_text(encoding='utf-8'))
        except Exception as e:
            print(f'   {p.name}: unreadable ({type(e).__name__}), skipped')
            continue
        actions = []
        walk(data, pairs, actions, fold=args.fold)
        hits = []
        if args.values:
            # Reported, never rewritten -- see LEAVE_ALONE, which carries the reason per file.
            spare = LEAVE_ALONE.get(p.name)
            retarget(data, pairs, hits, rewrite=(args.write and not spare))
            for h in hits:
                if spare:
                    h['wrote'] = False
                    h['writable'] = False
                    h['why'] = 'left alone -- ' + spare
        if not actions and not hits:
            continue
        touched += 1
        loud = [a for a in actions if not a['covered']]
        if loud:
            print(f'\n== {p.name}')
            for a in loud:
                print(f'   {a["path"]}.{a["retired"]} -> {a["keeper"]}: {a["action"]}')
                if a['extra']:
                    print(f'      keeper lacks these keys: {a["extra"]}')
                if a['filled']:
                    print(f'      keeper has these empty : {a["filled"]}')
                if a.get('appended'):
                    print(f'      appended {a["appended"]} item(s) to the keeper\'s list')
                if a['dropped'] and not a['folded']:
                    print(f'      DROPPED: {a["dropped"]}')
        if hits:
            print(f'\n== {p.name}  ({len(hits)} slug value(s))')
            # A hundred identical rows are one fact. _water_bindings_review.json holds 136 and
            # they buried the six that mattered the first time this printed.
            for h in hits[:VALUE_LINES]:
                print(f'   {h["kind"]:<11} {h["path"]}')
                print(f'      {h["retired"]} -> {h["keeper"]}: {h["why"]}')
                if h.get('detail'):
                    print(f'      {h["detail"]}')
            if len(hits) > VALUE_LINES:
                rest = {}
                for h in hits[VALUE_LINES:]:
                    k = (h['kind'], h['retired'], h['keeper'])
                    rest[k] = rest.get(k, 0) + 1
                print(f'   ... and {len(hits) - VALUE_LINES} more:')
                for (kind, r, k), n in sorted(rest.items(), key=lambda x: -x[1]):
                    print(f'      {n:>4} x {kind:<11} {r} -> {k}')
        total.extend([dict(a, file=p.name) for a in actions])
        vhits.extend([dict(h, file=p.name) for h in hits])
        if args.write and (actions or any(h['wrote'] for h in hits)):
            shutil.copy2(p, p.with_suffix('.json.bak'))
            p.write_text(json.dumps(data, indent=1), encoding='utf-8')
            written += 1

    renamed = sum(1 for a in total if a['action'] == 'renamed onto the keeper')
    quiet = sum(1 for a in total if a['covered'] and a['action'] != 'renamed onto the keeper')
    folded = sum(1 for a in total if a['folded'])
    lost = sum(1 for a in total if not a['covered'] and not a['folded'])
    print(f'\n== {touched} file(s) affected')
    print(f'   {renamed:>4} renamed onto the keeper (the keeper had no entry)')
    print(f'   {quiet:>4} collision(s) carrying nothing the keeper lacks -- no action needed')
    if folded:
        print(f'   {folded:>4} collision(s) FOLDED into the keeper')
    if lost:
        print(f'   {lost:>4} collision(s) holding content the keeper lacks, listed above.')
        print('        Re-run with --fold to copy those keys across, or leave them if the')
        print('        retired entry describes something being deleted anyway.')
    else:
        print('      0 collisions would lose anything.')

    if args.values:
        by = {}
        for h in vhits:
            by[h['kind']] = by.get(h['kind'], 0) + 1
        print(f'\n== {len(vhits)} slug value(s) in {len({h["file"] for h in vhits})} file(s)')
        for k in ('list-item', 'field', 'identity', 'zombie-row'):
            if by.get(k):
                print(f'   {by[k]:>4} {k}')
        # `wrote` is False for EVERYTHING on a dry run, so counting it here answered
        # "nothing was written" -- true, and not the question. `writable` is what --write would
        # actually do, which is the only number that previews anything.
        can = sum(1 for h in vhits if h['writable'])
        stuck = [h for h in vhits if not h['writable']]
        verb = 'rewritten' if args.write else 'would be rewritten'
        print(f'   {can:>4} {verb}')
        if stuck:
            print(f'   {len(stuck):>4} left alone -- listed above with the reason')
        # A row in a LEAVE_ALONE file is not deletion-tab material. Those files are regenerated
        # or gated somewhere else -- lakes.json by consolidate_lake_index.py:drop_retired(), the
        # reports by re-running whatever wrote them -- and listing their rows here would ask
        # Ryan to delete by hand what a build already handles.
        zom = [h for h in vhits if h['kind'] == 'zombie-row' and h['file'] not in LEAVE_ALONE]
        if zom:
            print('\n   ZOMBIE ROWS FOR registry/_deletion_tab.json -- a record for a slug that no')
            print('   longer exists, sitting in the same list as the keeper that replaced it.')
            print('   Nothing is deleted here.')
            for h in zom:
                print(f'      {h["file"]:<22} {h["path"]:<22} {h["retired"]} -> {h["keeper"]}')
        obs = sorted({h['file'] for h in vhits if h['file'] in LEAVE_ALONE})
        if obs:
            print(f'\n   {len(obs)} file(s) reported and left alone:')
            for f in obs:
                print(f'      {f:<28} {LEAVE_ALONE[f]}')
    elif not args.values:
        print('\n   note: KEYS only. Slug VALUES -- list items, alias_of, slug_to_r2_key, the slug')
        print('   field inside an already-renamed record -- are not looked at without --values.')

    if args.boundaries:
        bres, bnote = carry_boundaries(reg_dir, pairs, args.adopt_min_cover, args.write)
        print('\n== boundary files -- neither a key nor a value')
        if bnote:
            print('   !! %s' % bnote)
        if not bres:
            print('   nothing to carry: every keeper already traces at least as much water')
        for r in bres:
            verb = 'ADOPTED' if r['adopted'] else ('would adopt' if 'adds' in r.get('why', '')
                                                   else 'left alone')
            print('   %-9s %-24s <- %-24s' % (verb, r['keeper'], r['retired']))
            print('      %s' % r.get('why', ''))
            if 'lost_pct' in r:
                print('      %.2f%% of the old trace is outside the new one and is being dropped'
                      % r['lost_pct'])
        if any(r['adopted'] for r in bres):
            print('   THE CHARTPACK WAS CUT TO THE OLD BOUNDARY. Rebuild every adopted slug '
                  'before publishing.')

    if args.write:
        # `touched` counts files that HAD a hit; the LEAVE_ALONE ones are only reported.
        # Printing it here claimed nine files were written when six were, on the same run whose
        # block above says three were left alone. A closing count that contradicts the report
        # is the line someone quotes later.
        print(f'\nwrote {written} file(s), each with a .bak beside it')
        if touched > written:
            print(f'   {touched - written} more had a slug value that was reported and not '
                  f'rewritten -- nothing was written to those, and they have no .bak')
    else:
        print('\nDRY RUN -- nothing written. Add --write.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
