/** * catch-journal.js — Catch Journal with Zero-Friction Photo Import * * Stores structured catch data only — NO photos in IndexedDB. * Photos are used transiently to extract EXIF metadata, then discarded. * * Per-catch record schema: * species, length, time, depth, lure, lead, notes, * date, lake, lat, lon, * weather: { tempF, pressureHpa, cloudPct, windMph, moonPhase } * structure: { depthBand, nearestContour } * * Photo import pipeline (drag-drop or file picker): * 1. Read EXIF client-side (native browser API — no CDN library) * 2. GPS coords → contour spatial lookup → lake + depth band * 3. Timestamp + coords → Open-Meteo historical API → weather * 4. Timestamp → moon phase (pure math) * 5. Pre-fill catch form, discard photo blob */ import { state } from '../core/state.js'; import { esc } from '../utils/escape.js'; // ── State helpers ───────────────────────────────────────────────────────────── function getCatches() { return state.CATCHES; } function setCatches(arr) { state.CATCHES = arr; } // Pending data from photo import — cleared after save const pending = { lat: null, lon: null, weather: null, structure: null, photoThumb: null }; // ── IDB persistence ─────────────────────────────────────────────────────────── async function saveCatches() { if (!window.DB?.db) return; try { await window.DB.put('journal', { name: 'catches', data: getCatches() }); } catch (_) {} } export async function loadCatches() { if (!window.DB?.db) return; try { const r = await window.DB.get('journal', 'catches'); console.log('[IDB] catches found:', r ? (r.data?.length || 0) : 0); if (r) setCatches(r.data || []); renderCatchLog(); } catch (_) {} } // ── Catch log renderer ──────────────────────────────────────────────────────── export function renderCatchLog() { const host = document.getElementById('catchLog'); if (!host) return; const catches = getCatches(); if (!catches.length) { host.innerHTML = '<p class="muted" style="font-size:12px">No catches logged yet.</p>'; return; } host.innerHTML = catches.map((c, i) => ` <div style="display:flex;align-items:flex-start;gap:8px;padding:6px 0;border-bottom:1px solid var(--line);font-size:12px"> <span style="font-size:16px">🐟</span> <div style="flex:1;min-width:0"> <div><b>${esc(c.species || 'Fish')}</b>${c.length ? ' · ' + c.length + '"' : ''} · ${esc(c.time || '')} · ${esc(c.lake || '')}</div> <div style="color:var(--muted);font-size:11px;margin-top:2px"> ${c.depth ? 'Depth: ' + c.depth + 'ft' : ''} ${c.lure ? ' · ' + esc(c.lure) : ''} ${c.lead ? ' · Lead: ' + c.lead + 'ft' : ''} </div> ${c.weather ? `

${c.weather.tempF}°F · ${c.weather.pressureHpa} hPa · Wind ${c.weather.windMph}mph · ${c.weather.cloudPct}% cloud · ${esc(c.weather.moonPhase || '')}

` : ''} ${c.structure?.depthBand ? `

📍 ${esc(c.structure.depthBand)}

` : ''} ${c.notes ? `

${esc(c.notes)}

` : ''} </div> <button data-ci="${i}" style="padding:1px 6px;font-size:11px;flex-shrink:0">🗑</button> </div> `).join(''); host.querySelectorAll('[data-ci]').forEach(el => { el.addEventListener('click', async e => { const catches = getCatches(); catches.splice(+e.currentTarget.dataset.ci, 1); renderCatchLog(); await saveCatches(); }); }); } // ── Save new catch ───────────────────────────────────────────────────────────── async function saveNewCatch() { const catches = getCatches(); catches.unshift({ species: document.getElementById('cSpecies')?.value || '', length: document.getElementById('cLength')?.value || '', depth: document.getElementById('cDepth')?.value || '', lure: document.getElementById('cLure')?.value || '', lead: document.getElementById('cLead')?.value || '', time: document.getElementById('cTime')?.value || '', notes: document.getElementById('cNotes')?.value || '', date: document.getElementById('cDate')?.value || new Date().toISOString().slice(0, 10), lake: document.getElementById('planLake')?.value || '', lat: pending.lat || '', lon: pending.lon || '', weather: pending.weather || null, structure: pending.structure || null, }); // Clear pending — photo blob is discarded here, nothing stored pending.lat = null; pending.lon = null; pending.weather = null; pending.structure = null; pending.photoThumb = null; // Clear thumbnail preview and coords display const thumb = document.getElementById('cPhotoThumb'); if (thumb) { thumb.src = ''; thumb.style.display = 'none'; } const status = document.getElementById('cImportStatus'); if (status) status.textContent = ''; const coordEl4 = document.getElementById('cCoords'); if (coordEl4) coordEl4.value = ''; renderCatchLog(); await saveCatches(); // Reset form fields ['cSpecies','cLength','cDepth','cLure','cLead','cNotes','cDate'].forEach(id => { const el = document.getElementById(id); if (el) el.value = ''; }); const photoInput = document.getElementById('cPhoto'); if (photoInput) photoInput.value = ''; document.getElementById('catchForm').style.display = 'none'; } // ── EXIF extraction via exifr ──────────────────────────────────────────────── // exifr is a well-tested, actively maintained EXIF library available as a // pu
