/**
 * Garmin-formatted GPX export.
 *
 * Same data as `buildGPX` in parsers.js, but with Garmin-specific
 * extensions (gpxx namespace, DisplayColor, type="user" on waypoints)
 * so chartplotters render symbols + colors properly instead of
 * treating everything as generic.
 */

import { state } from '../core/state.js';
import { esc } from '../utils/escape.js';

// Garmin symbol mapping — common TrollMap symbol names to Garmin's
// built-in symbol IDs.
const GARMIN_SYMBOL_MAP = {
  'Waypoint': 'Waypoint',
  'Fishing Hot Spot Facility': 'Fishing Hot Spot Facility',
  'Anchor': 'Anchor',
  'Boat Ramp': 'Boat Ramp',
  'Buoy, White': 'Buoy, White',
  'danger': 'Skull and Crossbones',
  'Fish': 'Fish',
};

function garminSymbol(s) {
  return GARMIN_SYMBOL_MAP[s] || 'Fishing Hot Spot Facility';
}

/**
 * Trigger a download of `state.DATA` as a Garmin-flavored GPX file.
 * Filename comes from the plan name (with whitespace → underscores),
 * or "fishing_plan" if not set.
 */
export function exportGarminGPX() {
  if (!state.DATA.waypoints.length && !state.DATA.tracks.length) {
    alert('No waypoints or tracks to export');
    return;
  }

  const wptXml = state.DATA.waypoints.map((w) => `  <wpt lat="${w.lat.toFixed(7)}" lon="${w.lon.toFixed(7)}">
    <name>${esc(w.name || 'WPT')}</name>
    <sym>${garminSymbol(w.sym)}</sym>
    <type>user</type>
  </wpt>`).join('\n');

  const trkXml = state.DATA.tracks.map((t) => `  <trk>
    <name>${esc(t.name || 'Track')}</name>
    <extensions><gpxx:TrackExtension><gpxx:DisplayColor>Cyan</gpxx:DisplayColor></gpxx:TrackExtension></extensions>
    <trkseg>
${t.pts.map((p) => `      <trkpt lat="${p[0].toFixed(7)}" lon="${p[1].toFixed(7)}"></trkpt>`).join('\n')}
    </trkseg>
  </trk>`).join('\n');

  const planName = document.getElementById('planName')?.value || 'Fishing Plan';
  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     creator="TrollMap GPX Studio — Garmin Export"
     version="1.1"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${esc(planName)}</name>
    <desc>Generated by TrollMap GPX Studio — ${new Date().toLocaleString()}</desc>
    <time>${new Date().toISOString()}</time>
  </metadata>
${wptXml}
${trkXml}
</gpx>`;

  const blob = new Blob([gpx], { type: 'application/gpx+xml' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = (planName || 'fishing_plan').replace(/\s+/g, '_') + '_Garmin.gpx';
  a.click();
  URL.revokeObjectURL(a.href);
}

document.getElementById('exportGarminBtn')?.addEventListener('click', exportGarminGPX);
